# Generated by Django 5.2.7 on 2025-11-18 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Password',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
