# Generated by Django 5.2.7 on 2025-11-19 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_base64',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='image_mime',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
