# Generated by Django 5.2.7 on 2025-11-19 21:34

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_item_image_base64_item_image_mime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image_base64',
        ),
        migrations.RemoveField(
            model_name='item',
            name='image_mime',
        ),
        migrations.AddField(
            model_name='item',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='request_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, help_text="Upload the item image (e.g., 'Kleenex.png').", null=True, upload_to=api.models.supply_item_upload_path),
        ),
    ]
