# Generated by Django 5.2.7 on 2025-11-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_itempopularity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplyrequest',
            options={},
        ),
        migrations.AddField(
            model_name='itempopularity',
            name='category',
            field=models.CharField(default='other', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itempopularity',
            name='item_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='supplyrequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='supplyrequest',
            name='user_id',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='itempopularity',
            unique_together={('item_name', 'category')},
        ),
        migrations.AlterModelTable(
            name='supplyrequest',
            table=None,
        ),
    ]
