# Generated by Django 5.2.7 on 2025-11-19 22:17

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_item_image_base64_remove_item_image_mime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UIAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('image', models.ImageField(upload_to=api.models.ui_asset_upload_path)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, help_text="Upload an image like 'Kleenex.png'", null=True, upload_to=api.models.supply_item_upload_path),
        ),
    ]
