# Generated by Django 5.2.7 on 2025-11-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_roomreservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('category', models.CharField(choices=[('closet', 'Storage Closet'), ('break', 'Break Room'), ('kcup', 'K-Cups')], max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/')),
            ],
        ),
    ]
