# Generated by Django 5.2.7 on 2025-12-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_bannerimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerimage',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bannerimage',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
