# Generated by Django 5.2.7 on 2025-11-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_category_alter_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomreservation',
            name='room',
            field=models.CharField(max_length=50),
        ),
    ]
