# Generated by Django 5.2.7 on 2025-12-11 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_bannerimage_end_date_bannerimage_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='room',
            name='has_hdmi',
        ),
        migrations.RemoveField(
            model_name='room',
            name='has_screen',
        ),
        migrations.AddField(
            model_name='room',
            name='services',
            field=models.ManyToManyField(blank=True, to='api.roomservice'),
        ),
    ]
