# Generated by Django 5.2.7 on 2025-12-11 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_roomservice_remove_room_has_hdmi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='roomreservation',
            name='purpose',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
