# Generated by Django 5.2.7 on 2025-12-12 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_room_notes_roomreservation_purpose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='services',
        ),
        migrations.RemoveField(
            model_name='room',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='roomreservation',
            name='purpose',
        ),
        migrations.AddField(
            model_name='room',
            name='has_hdmi',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='has_screen',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='RoomService',
        ),
    ]
