# Generated by Django 5.2.7 on 2025-12-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_room_services_remove_room_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerimage',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
