# Generated by Django 5.2.7 on 2025-12-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerimage',
            name='repeat_yearly',
            field=models.BooleanField(default=False),
        ),
    ]
