# Generated by Django 5.2.7 on 2025-11-29 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='must_set_password',
            field=models.BooleanField(default=False),
        ),
    ]
