# Generated by Django 5.2.7 on 2025-12-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercard',
            name='raw_swipe',
            field=models.TextField(blank=True, null=True),
        ),
    ]
